# Change these first
owner: heygsiri # Your GitHub organization or username, where this repository lives
repo: upd-uptime # The name of this repository

sites:
  - name: UVLe
    url: https://uvle.upd.edu.ph
  - name: CRS
    url: https://crs.upd.edu.ph

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  # cname: upd-uptime.github.io
  baseUrl: /upd-uptime
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: UPD Uptime
  introTitle: "**UPD Uptime** displays the uptime of various UP Diliman-related services"
  introMessage: This is a sample status page which uses **real-time** data from our [GitHub repository](https://github.com/heygsiri/upd-uptime). No server required — just GitHub Actions, Issues, and Pages. [**Get your own for free**](https://github.com/upptime/upptime)
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
